### ISSUE TITLE
question : I got some errors.

### ISSUE THREAD

**Issue by manawo** [alefragnani/vscode-project-manager#198]
Hello, @alefragnani :)
Thank you for making PM8!!
When I update PM8, I got this errors. I cloud not see the folder icon at activity bar, also. 
I'm using High Sierra (10.13.5) , VSC 1.22.1 , PM8. What should I do for this case?

[![Screenshot from Gyazo](https://gyazo.com/d81c8d8b90543dd20a7b91d075c97021/raw)](https://gyazo.com/d81c8d8b90543dd20a7b91d075c97021)

**Comment by alefragnani** [comment]
Hi @manawo ,

Have you experienced any error message while updating the extension? Could you provide the `Console` log in `Toggle Developer Tools`? Maybe this could help to understand what's going on...

Another idea, you could uninstall and reinstall the extension. This could _force_ the extension to be installed entirely, in case some problem has hapened while updating.

Hope this helps

**Comment by manawo** [comment]
Hi @alefragnani ,
Thank you for replay 😊

> Have you experienced any error message while updating the extension?

No, I have not ☺️

here is console errors.
[![Screenshot from Gyazo](https://gyazo.com/a766e18d7b2e0a329ed1394d53d22544/raw)](https://gyazo.com/a766e18d7b2e0a329ed1394d53d22544)

so, Does that mean I do not have this `workbench.main.js` ?

> Another idea, you could uninstall and reinstall the extension. This could force the extension to be installed entirely, in case some problem has hapened while updating.

I already tried this 😊 but It not changed.
but,  I do not want to rush you.  If you have any solutions, let me know. I'm using another pc till that! time 🙋‍♀️

Thank you ☺️

**Comment by xiaoouwang** [comment]
same error here 💃

**Comment by alefragnani** [comment]
Hi @xiaoouwang ,

Are you using a Mac too?

**Comment by xiaoouwang** [comment]
Yes @alefregnani

**Comment by alefragnani** [comment]
Well, it appears to be a problem exclusive to Mac OS. At least, all of you are using it.

Unfortunately, I don't have access to a Mac to test. I will search for any references on this errors that could give me a glimpse of what's going on.

Just out of curiosity. Do you use the _normal_ installers, right? I mean, oficial installers, and not something like Chocolatey or Portable Mode?

It would also help if you could paste the contents of `package.json` file presented in `alefragnani.project-manager-8.0.0` folder, inside your _Extensions Folder_. You could access this folder right from the command palette `Extensions: Open Extensions Folder`. Just to be sure that the extension effectively installed the extension.

Hope this helps

**Comment by xiaoouwang** [comment]
{
	"name": "project-manager",
	"displayName": "Project Manager",
	"description": "Easily switch between projects",
	"version": "8.0.0",
	"publisher": "alefragnani",
	"galleryBanner": {
		"color": "#000000",
		"theme": "dark"
	},
	"engines": {
		"vscode": "^1.21.0"
	},
	"categories": [
		"Other"
	],
	"keywords": [
		"project",
		"folder",
		"switch",
		"manage",
		"git",
		"multi-root ready"
	],
	"icon": "images/icon.png",
	"license": "SEE LICENSE IN LICENSE.md",
	"homepage": "https://github.com/alefragnani/vscode-project-manager/blob/master/README.md",
	"repository": {
		"type": "git",
		"url": "https://github.com/alefragnani/vscode-project-manager.git"
	},
	"bugs": {
		"url": "https://github.com/alefragnani/vscode-project-manager/issues"
	},
	"activationEvents": [
		"*",
		"onCommand:projectManager.saveProject",
		"onCommand:projectManager.listProjects",
		"onCommand:projectManager.listProjectsNewWindow",
		"onCommand:projectManager.editProjects",
		"onCommand:projectManager.refreshProjects",
		"onView:projectsExplorer"
	],
	"main": "./out/src/extension",
	"contributes": {
		"viewsContainers": {
			"activitybar": [
				{
					"id": "project-manager",
					"title": "Project Manager",
					"icon": "images/ico-favorites-dark.svg"
				}
			]
		},
		"views": {
			"project-manager": [
				{
					"id": "projectsExplorerFavorites",
					"name": "Favorites",
					"when": "projectManager.canShowTreeViewFavorites"
				},
				{
					"id": "projectsExplorerGit",
					"name": "Git",
					"when": "projectManager.canShowTreeViewGit"
				},
				{
					"id": "projectsExplorerSVN",
					"name": "SVN",
					"when": "projectManager.canShowTreeViewSVN"
				},
				{
					"id": "projectsExplorerMercurial",
					"name": "Mercurial",
					"when": "projectManager.canShowTreeViewMercurial"
				},
				{
					"id": "projectsExplorerVSCode",
					"name": "VSCode",
					"when": "projectManager.canShowTreeViewVSCode"
				}
			]
		},
		"commands": [
			{
				"command": "projectManager.saveProject",
				"title": "Project Manager: Save Project"
			},
			{
				"command": "projectManager.listProjects",
				"title": "Project Manager: List Projects to Open"
			},
			{
				"command": "projectManager.listProjectsNewWindow",
				"title": "Project Manager: List Projects to Open in New Window"
			},
			{
				"command": "projectManager.editProjects",
				"title": "Project Manager: Edit Projects",
				"icon": {
					"light": "images/ico-edit-projects-light.svg",
					"dark": "images/ico-edit-projects-dark.svg"
				}
			},
			{
				"command": "projectManager.refreshProjects",
				"title": "Project Manager: Refresh Projects"
			},
			{
				"command": "projectManager.open",
				"title": "Open"
			},
			{
				"command": "projectManager.openInNewWindow",
				"title": "Open in New Window"
			},
			{
				"command": "projectManager.addToWorkspace",
				"title": "Add to Workspace"
			},
			{
				"command": "projectManager.deleteProject",
				"title": "Delete Project"
			},
			{
				"command": "projectManager.renameProject",
				"title": "Rename Project"
			}
		],
		"menus": {
			"commandPalette": [
				{
					"command": "projectManager.open",
					"when": "false"
				},
				{
					"command": "projectManager.openInNewWindow",
					"when": "false"
				},
				{
					"command": "projectManager.addToWorkspace",
					"when": "false"
				},
				{
					"command": "projectManager.deleteProject",
					"when": "false"
				},
				{
					"command": "projectManager.renameProject",
					"when": "false"
				}
			],
			"view/title": [
				{
					"command": "projectManager.editProjects",
					"when": "view == projectsExplorerFavorites",
					"group": "navigation"
				}
			],
			"view/item/context": [
				{
					"command": "projectManager.open",
					"when": "view =~ /projectsExplorer(Favorites|VSCode|Git|SVN|Mercurial)/",
					"group": "navigation"
				},
				{
					"command": "projectManager.openInNewWindow",
					"when": "view =~ /projectsExplorer(Favorites|VSCode|Git|SVN|Mercurial)/",
					"group": "navigation"
				},
				{
					"command": "projectManager.addToWorkspace",
					"when": "view =~ /projectsExplorer(Favorites|VSCode|Git|SVN|Mercurial)/",
					"group": "workspace"
				},
				{
					"command": "projectManager.deleteProject",
					"when": "view == projectsExplorerFavorites",
					"group": "favorites"
				},
				{
					"command": "projectManager.renameProject",
					"when": "view == projectsExplorerFavorites",
					"group": "favorites"
				}
			]
		},
		"configuration": {
			"type": "object",
			"title": "Project Manager Configuration",
			"properties": {
				"projectManager.showProjectNameInStatusBar": {
					"type": "boolean",
					"default": true,
					"description": "Should display the project name in the Status Bar?"
				},
				"projectManager.openInNewWindowWhenClickingInStatusBar": {
					"type": "boolean",
					"default": false,
					"description": "Should the project be opened using a New Window when you click the Status Bar?"
				},
				"projectManager.removeCurrentProjectFromList": {
					"type": "boolean",
					"default": true,
					"description": "Should the current project be hidden in the list of available projects?"
				},
				"projectManager.sortList": {
					"type": "string",
					"default": "Name",
					"description": "List the projects sorted by...(Saved, Name, Path or Recent)",
					"enum": [
						"Saved",
						"Name",
						"Path",
						"Recent"
					]
				},
				"projectManager.groupList": {
					"type": "boolean",
					"default": false,
					"description": "List the projects grouped by...(Favorites, VSCode, Git, Mercurial and SVN)"
				},
				"projectManager.projectsLocation": {
					"type": "string",
					"default": "",
					"description": "Indicates an alternative location where the `projects.json` file is stored"
				},
				"projectManager.vscode.baseFolders": {
					"type": "array",
					"default": [],
					"description": "Indicates the base folders to search for VSCode projects"
				},
				"projectManager.vscode.ignoredFolders": {
					"type": "array",
					"default": [
						"node_modules",
						"out",
						"typings",
						"test"
					],
					"description": "Indicates folders to be ignored, like \"node_modules\", \"out\", \"typings\", \"test\""
				},
				"projectManager.vscode.maxDepthRecursion": {
					"type": "integer",
					"default": 4,
					"description": "Indicates the maximum depth of folder recursion to search for projects. Any value below 1 means there is no limit"
				},
				"projectManager.git.baseFolders": {
					"type": "array",
					"default": [],
					"description": "Indicates the base folders to search for Git projects"
				},
				"projectManager.git.ignoredFolders": {
					"type": "array",
					"default": [
						"node_modules",
						"out",
						"typings",
						"test",
						".haxelib"
					],
					"description": "Indicates folders to be ignored, like \"node_modules\", \"out\", \"typings\", \"test\""
				},
				"projectManager.git.maxDepthRecursion": {
					"type": "integer",
					"default": 4,
					"description": "Indicates the maximum depth of folder recursion to search for projects. Any value below 1 means there is no limit"
				},
				"projectManager.hg.baseFolders": {
					"type": "array",
					"default": [],
					"description": "Indicates the base folders to search for Mercurial projects"
				},
				"projectManager.hg.ignoredFolders": {
					"type": "array",
					"default": [
						"node_modules",
						"out",
						"typings",
						"test",
						".haxelib"
					],
					"description": "Indicates folders to be ignored, like \"node_modules\", \"out\", \"typings\", \"test\""
				},
				"projectManager.hg.maxDepthRecursion": {
					"type": "integer",
					"default": 4,
					"description": "Indicates the maximum depth of folder recursion to search for projects. Any value below 1 means there is no limit"
				},
				"projectManager.svn.baseFolders": {
					"type": "array",
					"default": [],
					"description": "Indicates the base folders to search for SVN projects"
				},
				"projectManager.svn.ignoredFolders": {
					"type": "array",
					"default": [
						"node_modules",
						"out",
						"typings",
						"test"
					],
					"description": "Indicates folders to be ignored, like \"node_modules\", \"out\", \"typings\", \"test\""
				},
				"projectManager.svn.maxDepthRecursion": {
					"type": "integer",
					"default": 4,
					"description": "Indicates the maximum depth of folder recursion to search for projects. Any value below 1 means there is no limit"
				},
				"projectManager.cacheProjectsBetweenSessions": {
					"type": "boolean",
					"default": true,
					"description": "Should cache the VSCode, Git and SVN projects found?"
				},
				"projectManager.checkInvalidPathsBeforeListing": {
					"type": "boolean",
					"default": true,
					"description": "Should check for invalid paths before listing, showing a message below the project name?"
				},
				"projectManager.treeview.visible": {
					"type": "boolean",
					"default": true,
					"description": "Should display the Treeview?"
				},
				"projectManager.filterOnFullPath": {
					"type": "boolean",
					"default": false,
					"description": "Should filter projects through full path?"
				}
			}
		},
		"keybindings": [
			{
				"command": "projectManager.listProjects",
				"key": "shift+alt+p",
				"mac": "cmd+alt+p"
			}
		]
	},
	"scripts": {
		"vscode:prepublish": "tsc -p ./",
		"compile": "tsc -watch -p ./",
		"postinstall": "node ./node_modules/vscode/bin/install"
	},
	"devDependencies": {
		"@types/node": "^6.0.40",
		"typescript": "^2.3.2",
		"vscode": "^1.1.17"
	},
	"dependencies": {
		"walker": "^1.0.7"
	},
	"__metadata": {
		"id": "1b747f06-3789-4ebd-ac99-f1fe430c3347",
		"publisherId": "3fbdef65-bdf5-4723-aeaf-9e12a50546ef",
		"publisherDisplayName": "Alessandro Fragnani"
	}
}


Here it is ! Yes I did install via the official installer

**Comment by basvandenbrink** [comment]
I have the same error using Windows 10.

**Comment by jd-mtb** [comment]
I also have this issue on windows 7. I used the 'user' mode installer FYI! (installs to app data directory)

**Comment by dvdgsng** [comment]
Same errors here.

* Windows 10
* VSCode portable (just the extracted zip, not that PortableApps stuff or chocolatey)
* Extension directory is in homedir (ie: C:\Users\MYUSER\.vscode\extensions\alefragnani.project-manager-8.0.0)
* console output:
![image](https://user-images.githubusercontent.com/4592717/44541952-d5e78980-a70b-11e8-82ca-49705336e64b.png)

* Plugin package.json:
```
{
	"name": "project-manager",
	"displayName": "Project Manager",
	"description": "Easily switch between projects",
	"version": "8.0.0",
	"publisher": "alefragnani",
	"galleryBanner": {
		"color": "#000000",
		"theme": "dark"
	},
	"engines": {
		"vscode": "^1.21.0"
	},
	"categories": [
		"Other"
	],
	"keywords": [
		"project",
		"folder",
		"switch",
		"manage",
		"git",
		"multi-root ready"
	],
	"icon": "images/icon.png",
	"license": "SEE LICENSE IN LICENSE.md",
	"homepage": "https://github.com/alefragnani/vscode-project-manager/blob/master/README.md",
	"repository": {
		"type": "git",
		"url": "https://github.com/alefragnani/vscode-project-manager.git"
	},
	"bugs": {
		"url": "https://github.com/alefragnani/vscode-project-manager/issues"
	},
	"activationEvents": [
		"*",
		"onCommand:projectManager.saveProject",
		"onCommand:projectManager.listProjects",
		"onCommand:projectManager.listProjectsNewWindow",
		"onCommand:projectManager.editProjects",
		"onCommand:projectManager.refreshProjects",
		"onView:projectsExplorer"
	],
	"main": "./out/src/extension",
	"contributes": {
		"viewsContainers": {
			"activitybar": [
				{
					"id": "project-manager",
					"title": "Project Manager",
					"icon": "images/ico-favorites-dark.svg"
				}
			]
		},
		"views": {
			"project-manager": [
				{
					"id": "projectsExplorerFavorites",
					"name": "Favorites",
					"when": "projectManager.canShowTreeViewFavorites"
				},
				{
					"id": "projectsExplorerGit",
					"name": "Git",
					"when": "projectManager.canShowTreeViewGit"
				},
				{
					"id": "projectsExplorerSVN",
					"name": "SVN",
					"when": "projectManager.canShowTreeViewSVN"
				},
				{
					"id": "projectsExplorerMercurial",
					"name": "Mercurial",
					"when": "projectManager.canShowTreeViewMercurial"
				},
				{
					"id": "projectsExplorerVSCode",
					"name": "VSCode",
					"when": "projectManager.canShowTreeViewVSCode"
				}
			]
		},
		"commands": [
			{
				"command": "projectManager.saveProject",
				"title": "Project Manager: Save Project"
			},
			{
				"command": "projectManager.listProjects",
				"title": "Project Manager: List Projects to Open"
			},
			{
				"command": "projectManager.listProjectsNewWindow",
				"title": "Project Manager: List Projects to Open in New Window"
			},
			{
				"command": "projectManager.editProjects",
				"title": "Project Manager: Edit Projects",
				"icon": {
					"light": "images/ico-edit-projects-light.svg",
					"dark": "images/ico-edit-projects-dark.svg"
				}
			},
			{
				"command": "projectManager.refreshProjects",
				"title": "Project Manager: Refresh Projects"
			},
			{
				"command": "projectManager.open",
				"title": "Open"
			},
			{
				"command": "projectManager.openInNewWindow",
				"title": "Open in New Window"
			},
			{
				"command": "projectManager.addToWorkspace",
				"title": "Add to Workspace"
			},
			{
				"command": "projectManager.deleteProject",
				"title": "Delete Project"
			},
			{
				"command": "projectManager.renameProject",
				"title": "Rename Project"
			}
		],
		"menus": {
			"commandPalette": [
				{
					"command": "projectManager.open",
					"when": "false"
				},
				{
					"command": "projectManager.openInNewWindow",
					"when": "false"
				},
				{
					"command": "projectManager.addToWorkspace",
					"when": "false"
				},
				{
					"command": "projectManager.deleteProject",
					"when": "false"
				},
				{
					"command": "projectManager.renameProject",
					"when": "false"
				}
			],
			"view/title": [
				{
					"command": "projectManager.editProjects",
					"when": "view == projectsExplorerFavorites",
					"group": "navigation"
				}
			],
			"view/item/context": [
				{
					"command": "projectManager.open",
					"when": "view =~ /projectsExplorer(Favorites|VSCode|Git|SVN|Mercurial)/",
					"group": "navigation"
				},
				{
					"command": "projectManager.openInNewWindow",
					"when": "view =~ /projectsExplorer(Favorites|VSCode|Git|SVN|Mercurial)/",
					"group": "navigation"
				},
				{
					"command": "projectManager.addToWorkspace",
					"when": "view =~ /projectsExplorer(Favorites|VSCode|Git|SVN|Mercurial)/",
					"group": "workspace"
				},
				{
					"command": "projectManager.deleteProject",
					"when": "view == projectsExplorerFavorites",
					"group": "favorites"
				},
				{
					"command": "projectManager.renameProject",
					"when": "view == projectsExplorerFavorites",
					"group": "favorites"
				}
			]
		},
		"configuration": {
			"type": "object",
			"title": "Project Manager Configuration",
			"properties": {
				"projectManager.showProjectNameInStatusBar": {
					"type": "boolean",
					"default": true,
					"description": "Should display the project name in the Status Bar?"
				},
				"projectManager.openInNewWindowWhenClickingInStatusBar": {
					"type": "boolean",
					"default": false,
					"description": "Should the project be opened using a New Window when you click the Status Bar?"
				},
				"projectManager.removeCurrentProjectFromList": {
					"type": "boolean",
					"default": true,
					"description": "Should the current project be hidden in the list of available projects?"
				},
				"projectManager.sortList": {
					"type": "string",
					"default": "Name",
					"description": "List the projects sorted by...(Saved, Name, Path or Recent)",
					"enum": [
						"Saved",
						"Name",
						"Path",
						"Recent"
					]
				},
				"projectManager.groupList": {
					"type": "boolean",
					"default": false,
					"description": "List the projects grouped by...(Favorites, VSCode, Git, Mercurial and SVN)"
				},
				"projectManager.projectsLocation": {
					"type": "string",
					"default": "",
					"description": "Indicates an alternative location where the `projects.json` file is stored"
				},
				"projectManager.vscode.baseFolders": {
					"type": "array",
					"default": [],
					"description": "Indicates the base folders to search for VSCode projects"
				},
				"projectManager.vscode.ignoredFolders": {
					"type": "array",
					"default": [
						"node_modules",
						"out",
						"typings",
						"test"
					],
					"description": "Indicates folders to be ignored, like \"node_modules\", \"out\", \"typings\", \"test\""
				},
				"projectManager.vscode.maxDepthRecursion": {
					"type": "integer",
					"default": 4,
					"description": "Indicates the maximum depth of folder recursion to search for projects. Any value below 1 means there is no limit"
				},
				"projectManager.git.baseFolders": {
					"type": "array",
					"default": [],
					"description": "Indicates the base folders to search for Git projects"
				},
				"projectManager.git.ignoredFolders": {
					"type": "array",
					"default": [
						"node_modules",
						"out",
						"typings",
						"test",
						".haxelib"
					],
					"description": "Indicates folders to be ignored, like \"node_modules\", \"out\", \"typings\", \"test\""
				},
				"projectManager.git.maxDepthRecursion": {
					"type": "integer",
					"default": 4,
					"description": "Indicates the maximum depth of folder recursion to search for projects. Any value below 1 means there is no limit"
				},
				"projectManager.hg.baseFolders": {
					"type": "array",
					"default": [],
					"description": "Indicates the base folders to search for Mercurial projects"
				},
				"projectManager.hg.ignoredFolders": {
					"type": "array",
					"default": [
						"node_modules",
						"out",
						"typings",
						"test",
						".haxelib"
					],
					"description": "Indicates folders to be ignored, like \"node_modules\", \"out\", \"typings\", \"test\""
				},
				"projectManager.hg.maxDepthRecursion": {
					"type": "integer",
					"default": 4,
					"description": "Indicates the maximum depth of folder recursion to search for projects. Any value below 1 means there is no limit"
				},
				"projectManager.svn.baseFolders": {
					"type": "array",
					"default": [],
					"description": "Indicates the base folders to search for SVN projects"
				},
				"projectManager.svn.ignoredFolders": {
					"type": "array",
					"default": [
						"node_modules",
						"out",
						"typings",
						"test"
					],
					"description": "Indicates folders to be ignored, like \"node_modules\", \"out\", \"typings\", \"test\""
				},
				"projectManager.svn.maxDepthRecursion": {
					"type": "integer",
					"default": 4,
					"description": "Indicates the maximum depth of folder recursion to search for projects. Any value below 1 means there is no limit"
				},
				"projectManager.cacheProjectsBetweenSessions": {
					"type": "boolean",
					"default": true,
					"description": "Should cache the VSCode, Git and SVN projects found?"
				},
				"projectManager.checkInvalidPathsBeforeListing": {
					"type": "boolean",
					"default": true,
					"description": "Should check for invalid paths before listing, showing a message below the project name?"
				},
				"projectManager.treeview.visible": {
					"type": "boolean",
					"default": true,
					"description": "Should display the Treeview?"
				},
				"projectManager.filterOnFullPath": {
					"type": "boolean",
					"default": false,
					"description": "Should filter projects through full path?"
				}
			}
		},
		"keybindings": [
			{
				"command": "projectManager.listProjects",
				"key": "shift+alt+p",
				"mac": "cmd+alt+p"
			}
		]
	},
	"scripts": {
		"vscode:prepublish": "tsc -p ./",
		"compile": "tsc -watch -p ./",
		"postinstall": "node ./node_modules/vscode/bin/install"
	},
	"devDependencies": {
		"@types/node": "^6.0.40",
		"typescript": "^2.3.2",
		"vscode": "^1.1.17"
	},
	"dependencies": {
		"walker": "^1.0.7"
	},
	"__metadata": {
		"id": "1b747f06-3789-4ebd-ac99-f1fe430c3347",
		"publisherId": "3fbdef65-bdf5-4723-aeaf-9e12a50546ef",
		"publisherDisplayName": "Alessandro Fragnani"
	}
}
```

**Comment by alefragnani** [comment]
Hi,

First of all, sorry for the lack of news about this issue. In the recent weeks has been very difficult to find free time to work on the extensions 😢 

The good news is that last week I decided to "re-focus" on some of my extensions, and I'll start to plan milestones for each of them. But this "re-focus" will be based on community feedback/support, and I still don't know where the issue will be.

I would like to take the opportunity to ask if some of you does not experience the issue anymore, either after updating VS Code or with the latest update that I released yesterday.

Thank you

**Comment by basvandenbrink** [comment]
I can confirm that this issue still occurs with VS Code version 1.22.2 on Windows 10 (x64).

![image](https://user-images.githubusercontent.com/2811984/45845536-b604af00-bd25-11e8-9a0f-b57f5cddb3db.png)

**Comment by alefragnani** [comment]
Hi @basvandenbrink @manawo ,

Are you really using using version 1.**22**.X? Wasn't that a typo? I'm asking because the current release is 1.**27**.2.

I mean, the Activity Bar API was supposed to work from version 1.21^, but I'm not sure this was _public available_ or should be enabled as `experimental`. 

Depending on this, I could try to find the older installer and test with this older version

Hope this helps.

**Comment by basvandenbrink** [comment]
Hi @alefragnani ,

Ah, there is a new version available. Now I see (I thought I had used Chocolatey for installing and updating VS Code).

Problem solved!

**Comment by alefragnani** [comment]
I installed version 1.22.2 and could reproduce the problem. It's really related to the _supported API_. 

Unfortunately, I can't publish _previous versions_ of a package. So to solve that, you must update to a newer VSCode release. I think that at least 1.23.

I'll update the extension to fix this _min version_ issue.
